### ISSUE TITLE
optimize colors for viewing from colorblind, screen, b&w print, and color print

### ISSUE THREAD

**Issue by zachll** [Landis-Lewis-Lab/goals-of-care#13]

**Comment by zachll** [comment]
Optimize for viewing from colorblind, screen, b&w print, and color print

**Comment by grosscol** [comment]
The rcolorbrewer package provides some palettes optimized for cartography.  These palettes are available using the `scale_color_brewer` structure for use with ggplot2.

 e.g. The YlGnBu palette  http://colorbrewer2.org/#type=sequential&scheme=YlGnBu&n=3
