### ISSUE TITLE
Limit timeline for CLC memo displays to the previous 2 years

### ISSUE THREAD

**Issue by zachll** [Landis-Lewis-Lab/goals-of-care#30]

**Comment by grosscol** [comment]
This might be more appropriate to put on the end user.  They are supplying the source data, and I would expect them to be able to limit it to whatever time period is appropriate.

We can do this and include some documentation of the behavior in the readme, but it still might be surprising if a user attempts to use this report to reflect on a 3+ year effort.

**Comment by zachll** [comment]
It would be good to include this as a config option, with the default set to 2 years, regardless of the data being provided.
