### ISSUE TITLE
CLC report should indicate exclusion of short stay admits

### ISSUE THREAD

**Issue by zachll** [Landis-Lewis-Lab/goals-of-care#35]
add this sentence as an assist statement for all sites:

“Veterans admitted to short stay have been excluded from the data in this report.”

**Comment by grosscol** [comment]
This is for both the CLC and HBPC templates?
This seems like a candidate statement to add to the config in the assist statements.

**Comment by zachll** [comment]
Thanks - yes, this should be config-only
