### ISSUE TITLE
include facility name in file name

### ISSUE THREAD

**Issue by zachll** [Landis-Lewis-Lab/goals-of-care#48]
Having the report files contain the facility name in addition to or instead of the site id would improve the ability to recognize reports among the team and recipients.

**Comment by grosscol** [comment]
Not actually closed by #54.
Talked about this on the phone call last week.  This change is a convenience for the team discussing the reports.  The impact it would have on the process of sending them was unknown.

Implementation agreed upon was to read from the config for the site, then default to the id.  In that way, VA can specify what it wants to name the files, but has to do so manually.

That means that the settings yaml file will no longer just be influencing the report generation itself, but must be read and processed before being provided to the knitr engine.  This is related to #41.

**Comment by grosscol** [comment]
This change has been incorporated.
