### ISSUE TITLE
Report changes October 2018

### ISSUE THREAD

**Issue by zachll** [Landis-Lewis-Lab/goals-of-care#59]
Dementia/Project 2
The legends should be at the top, right below the text explaining what the graph shows

Standard CLC Report
- [x] Will show data by month (6 months of data will be shown on each report)
- [x] Will add the x-axis to both the top and bottom graphs on each page
- [x] Will change the y-axis label from “veterans count” to “Number of newly admitted Veterans”
- [x] The labels for the long stay graphs should be “Long-Term Care Residents” and the labels for short stay graphs should be “Short-Stay Patients”
- [x] Will remove bullets from page 2 and 3
- [x] Dates will be shown using 3 letter month abbreviation and year
- [x] Page 3 “for patients/residents with a documented GoCC when was the conversation documented”
- [x] Will put the CLC and date labels on the top of the page so that it’s easy for sites to view
- [x] Received feedback from sites that they want to see all of the numbers on the bars
- [x] Remove 4th page with a summary table that sites can use to look up the actual numbers and this will include % data

HBPC report

- [x] Will update formatting to match the CLC standard report
- [x] Will change “which visit were GoCC…” to reflect the CLC reports. Legend will be: before admission, the first visit, 2nd visit, and 4th or later visit
- [x] Will remove the bullets from below all the grahs
- [x] Dates will be shown using 3 letter month abbreviation and year
- [x] Will change “veterans count” to “number of newly admitted Veterans”
- [x] Will put the HBPC and date labels on the top of the page so that it’s easy for sites to view
- [x] Received feedback from sites that they want to see all of the numbers on the bars

**Comment by grosscol** [comment]
Addresses #53

**Comment by grosscol** [comment]
Added CLC and date labels as subtitles of plots to accommodate "date labels on top of the page"

**Comment by grosscol** [comment]
Removed printed table of values.
Nothing to be done for printing numbers on all the bars due.  Over plotting when bars are too small has not been resolved.

**Comment by grosscol** [comment]
>Will change “which visit were GoCC…” to reflect the CLC reports. Legend will be: before admission, the first visit, 2nd visit, and 4th or later visit

This needs to be checked that the incoming data actually reflects visit number.  The CLC reports are arranged by date.  Related to #58 in that having a code book to reference would have been useful right now.

**Comment by grosscol** [comment]
>Will change “veterans count” to “number of newly admitted Veterans”

This is too long for the space.  Using "Newly Admitted Veterans" as the y-axis label instead.

**Comment by grosscol** [comment]
Updated HBPC category labels.  As of c2844f4b96b7d380cb8ac9dae5270382f8a97c56 all the changes are in place.
