### ISSUE TITLE
increase margin for legend components 

### ISSUE THREAD

**Issue by zachll** [Landis-Lewis-Lab/goals-of-care#60]
The margin between text and the colored boxes on both sides could be increased to approximately match or exceed the spacing between the stacked bars for all reports

**Comment by grosscol** [comment]
Commit b2fa67fd196cc3eadd535684f4daaeba082cf6ff increases the spacing between legend text items.

Previous Margin:
![legend_no_margin](https://user-images.githubusercontent.com/1520508/48863152-675fa980-ed96-11e8-8c3f-25fb22138986.png)

Increased Margin:
![legend_margin](https://user-images.githubusercontent.com/1520508/48863173-70507b00-ed96-11e8-9b01-005ed33c4056.png)
